// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcgklnibxxkuazxaqhyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZ2tsbmlieHhrdWF6eGFxaHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDQ4ODUsImV4cCI6MjA1OTg4MDg4NX0.HdAyMt0MC7Ue0mBLVShO3eGKa1dbhmSuInVDIRQjDcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);